FROM apache/airflow:2.9.3
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

USER root

RUN python3 -m venv /opt/dbt_venv && \
    /opt/dbt_venv/bin/pip install --no-cache-dir \
        dbt-core==1.10.17 \
        dbt-snowflake==1.10.6
RUN chown -R airflow:root /opt/dbt_venv

USER airflow