-- 5, 20, 60, 120일 이동평균 계산
WITH ALL_CANDLE_MA AS (
    SELECT
        CODE, TRADE_DATE, OPEN_PRICE, CLOSE_PRICE,
        AVG(CLOSE_PRICE) OVER (
            PARTITION BY CODE
            ORDER BY TRADE_DATE
            ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS MA5,
        AVG(CLOSE_PRICE) OVER (
            PARTITION BY CODE
            ORDER BY TRADE_DATE
            ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS MA20,
        AVG(CLOSE_PRICE) OVER (
            PARTITION BY CODE
            ORDER BY TRADE_DATE
            ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS MA60,
        AVG(CLOSE_PRICE) OVER (
            PARTITION BY CODE
            ORDER BY TRADE_DATE
            ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS MA120
    FROM {{ source('silver', 'SILVER_CANDLES') }}
    WHERE CANDLE_INTERVAL = '1d'
)

-- 최근 6개월 데이터만 가져오기
SELECT *
FROM ALL_CANDLE_MA
WHERE TRADE_DATE >= DATEADD(DAY, -180, CURRENT_DATE())
ORDER BY CODE, TRADE_DATE
