-- 최근 7일의 시간별/요일별 거래량, 거래금액 가져오기
SELECT
    CODE,
    TRADE_DATE,
    DAYOFWEEK(TRADE_DATE) AS DAY_OF_WEEK,
    EXTRACT(HOUR FROM CANDLE_TS) AS HOUR,
    VOLUME,
    TRADE_PRICE
FROM {{ source('silver', 'SILVER_CANDLES') }}
WHERE CANDLE_INTERVAL = '1h' AND TRADE_DATE >= DATEADD(DAY, -7, CURRENT_DATE())
ORDER BY TRADE_DATE, CODE, DAY_OF_WEEK, HOUR
