-- 비트코인의 요일/시간별 매도/매수량, 체결 강도 계산
WITH HOURLY_AGG AS (
    SELECT
        TRADE_DATE,
        DAYOFWEEK(TRADE_DATE) AS DAY_OF_WEEK,
        EXTRACT(HOUR FROM TRADE_TS) AS HOUR,
        SUM(CASE WHEN ASK_BID = 'ASK' THEN TRADE_VOLUME ELSE 0 END) AS SELL_VOLUME,
        SUM(CASE WHEN ASK_BID = 'BID' THEN TRADE_VOLUME ELSE 0 END) AS BUY_VOLUME,

    FROM {{ source('silver', 'SILVER_TRADES') }}

    WHERE
        CODE = 'KRW-BTC' AND
        (EXTRACT(HOUR FROM TRADE_TS) >= 22 OR EXTRACT(HOUR FROM TRADE_TS) < 2)

    GROUP BY
        TRADE_DATE,
        DAY_OF_WEEK,
        EXTRACT(HOUR FROM TRADE_TS)
)

-- 최근 7일 데이터만 가져옴 (일주일 간격 유지)
SELECT
    TRADE_DATE,
    DAY_OF_WEEK,
    HOUR,
    SELL_VOLUME,
    BUY_VOLUME,
    (BUY_VOLUME / SELL_VOLUME) * 100 AS TRADE_STRENGTH
FROM HOURLY_AGG
WHERE TRADE_DATE >= DATEADD(DAY, -6, CURRENT_DATE())
