name: 'upbit_dbt'
version: '1.0.0'

profile: 'upbit_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  upbit_dbt:
    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
