version: 2

sources:
  - name: silver
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
    tables:
      - name: SILVER_CANDLES
      - name: BRONZE_TICKER


